# 视觉处理配置
system:
  name: 'Drone_Vision_System'
  version: '1.0.0'

optical_flow:
  model_path: 'models/raft/raft.pth'
  device: 'cuda'
  iters: 20

depth_estimation:
  model_path: 'models/monodepth2/'
  input_width: 640
  input_height: 192
  min_depth: 0.1
  max_depth: 100.0
  scale_factor: 5.4
  device: 'cuda'

clustering:
  method: 'kmeans'
  n_clusters: 3
  grid_step: 8

camera:
  intrinsic:
    fx: 600.0
    fy: 600.0
    cx: 320.0
    cy: 240.0
  resolution: [640, 480]

output:
  save_results: true
  visualize: true
  save_format: 'both'
  display_results: true